### ISSUE TITLE
narrow build dependency on HTTP

### ISSUE THREAD

**Issue by clinty** [bsl/oeis#5]
oeis conflicts with HTTP 4000.3.3

**Comment by nomeata** [comment]
What Clint wants to say is that you should expand your build dependency to include the latest release. And please also join stackage so that such breakage is detected early: http://www.stackage.org/authors

**Comment by nomeata** [comment]
BTW, it builds against `4000.3.3` without changes to the source code.

**Comment by bsl** [comment]
Hi, thanks for letting me know. I'm sorry I haven't kept this package updated.

The problem is, my life is very different than it was back when I was working with Haskell. Do you have any interest in taking over maintainership?

**Comment by nomeata** [comment]
Not me, I’m just reporting this as I am maintaining the Debian packages, and have not personal interested in oeis. You should ask on the haskell-cafe mailing list.

**Comment by niteria** [comment]
This issue will block adding `lambdabot` to stackage. This package seems low maintenance, I can try being a maintainer.

**Comment by bsl** [comment]
Thanks. I added you as a collaborator. Do you have a Hackage account? I'm not seeing it.

**Comment by niteria** [comment]
I've just created a Hackage account: http://hackage.haskell.org/user/niteria

**Comment by bsl** [comment]
You should be good to go. Thanks again.

**Comment by niteria** [comment]
Thank you!
